server:
  port: 8002
spring:
  application:
    name: eureka-consumer-02
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
